version: '3.9'

services:
  db:
    image: postgres:12.4-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data_todolist:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      timeout:  3s
      retries: 3
    ports:
      - "5432:5432"
    networks:
      - backend_nw


volumes:
  postgres_data_todolist:

networks:
  backend_nw:
    driver: bridge

